travis:
  secure:
    BINSTAR_TOKEN: xhloTL1QxtmsC6lscGgt2yK/uAg1oy2MmkemaXb3wPoZSXZOcdXHK70xud2+Tq8napbc47tFIUm18ap0KEHpVRs5azkv6ZCJb87P3DJcmbj5+HoKvXsLnXYfPjT9Ru/tpnQtkMqdwEaGn/m4A4Ume1avLD/C0KxTSw5kSVg2wcAeS+H939pgBSpoW32gxAefAL3IraJNyuF0oAxYNg9373EMRoYMPq9P8Ph/8cB9ym9zzpLwToFNQmp8u2xoJ5jhI8SvjokKFPSwbu+jE/MVA9BDwk5AhA5NJmdELF10kIHyr40JuQJGSlir9mKcL4Ud+OqFlFcnPRmBULeJN9yDwlJjXDc3mPGmB4VKM8eM/jK3P/8YTo94rvM2aVVE+J5mqD2++6qsUOCrG1n65UXtcyi7AypHXx14E70a06BDPS1bTh5uJw7pxi5CzPunyUBjp9akSQ3hfkhUuxdIf6Am3g4VttLXFs0AA+NWLnJEPA/oEgBm20CZs5NtIpbxR79mzjhsqlTISkPAlXDvrhoKRBsxnfYDlq4xJdiBMisqub/ts2SUd0VXXqk4aooqvqbQ5oy66uVrP2HT5KtsrR3pUNGP4cPxEg4LVv88EeWnSGBfXUHBoooAbtqQ9RfI9bYVNGqiXfZ12kw1tuF/hrsv+UJFUuR5mzNWYiRbRl3vpYg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
